package todo.view;

import java.awt.Color;
import java.text.SimpleDateFormat;
import org.openide.util.Exceptions;
import org.openide.util.Lookup;
import todo.model.Task;
import todo.model.TaskManagerInterface;
import todo.model.ValidationException;

/**
 *
 * @author lozano, ikost
 */
public class TaskDetailsDialog extends javax.swing.JDialog {

    private Task task;
    private boolean isNewTask;
    private final TaskManagerInterface taskManager;

    public void setNewTask(boolean newTask) {
        this.isNewTask = newTask;
        remove.setEnabled(!newTask);
        if (isNewTask()) {
            setMessage("Fill in the new task information", false);
        } else {
            setMessage("Changing task information", false);
        }
    }

    public boolean isNewTask() {
        return isNewTask;
    }

    public void setMessage(String msg, boolean isError) {
        message.setText(msg);
        if (isError) {
            message.setForeground(Color.RED);
        } else {
            message.setForeground(Color.DARK_GRAY);
        }
    }

    public void setTask(Task task) {
        this.task = task;
        description.setText(task.getDescription());
        priority.setValue(task.getPriority());
        completed.setSelected(task.isCompleted());
        dueDate.setDate(task.getDueDate());
        alert.setSelected(task.getAlert());
        daysBefore.setEnabled(task.getAlert());
        alertLabel.setEnabled(task.getAlert());
        daysBefore.setValue(task.getDaysBefore());
        obs.setText(task.getObs());
    }

    public Task getTask() {
        task.setDescription(description.getText());
        task.setPriority(((Number) priority.getValue()).intValue());
        task.setCompleted(completed.isSelected());
        task.setDueDate(dueDate.getDate());
        task.setAlert(alert.isSelected());
        task.setDaysBefore(((Number) daysBefore.getValue()).intValue());
        task.setObs(obs.getText());
        return task;
    }

    public TaskDetailsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        taskManager = Lookup.getDefault().lookup(TaskManagerInterface.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        message = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        priority = new javax.swing.JSpinner();
        alert = new javax.swing.JCheckBox();
        daysBefore = new javax.swing.JSpinner();
        alertLabel = new javax.swing.JLabel();
        completed = new javax.swing.JCheckBox();
        remove = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        obs = new javax.swing.JTextArea();
        dueDate = new org.jdesktop.swingx.JXDatePicker();
        dueDate.setFormats(new SimpleDateFormat("dd/MM/yyyy"));

        FormListener formListener1 = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Task Details");

        message.setBackground(new java.awt.Color(255, 255, 255));
        message.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        message.setText("Fill in the new task information");
        message.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        message.setOpaque(true);

        jLabel2.setDisplayedMnemonic('D');
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Description:");

        jLabel3.setDisplayedMnemonic('P');
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Priority:");

        jLabel4.setDisplayedMnemonic('u');
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Due Date:");

        priority.addChangeListener(formListener1);

        alert.setMnemonic('a');
        alert.setText("Show alert:");
        alert.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        alert.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        alert.setMargin(new java.awt.Insets(0, 0, 0, 0));
        alert.addActionListener(formListener1);

        daysBefore.addChangeListener(formListener1);

        alertLabel.setText("days before");

        completed.setMnemonic('T');
        completed.setText("Completed task");
        completed.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        completed.setMargin(new java.awt.Insets(0, 0, 0, 0));

        remove.setMnemonic('R');
        remove.setText("Remove");
        remove.setActionCommand("removeTask");
        remove.addActionListener(formListener1);

        cancel.setMnemonic('N');
        cancel.setText("Cancel");
        cancel.addActionListener(formListener1);

        save.setMnemonic('S');
        save.setText("Save");
        save.setActionCommand("saveTask");
        save.addActionListener(formListener1);

        jLabel6.setDisplayedMnemonic('O');
        jLabel6.setText("Obs:");

        obs.setColumns(20);
        obs.setRows(5);
        jScrollPane1.setViewportView(obs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(alert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(description, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(daysBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(alertLabel))
                                    .addComponent(priority, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 420, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(completed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remove))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancel, remove, save});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(priority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alert)
                    .addComponent(alertLabel)
                    .addComponent(daysBefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remove)
                    .addComponent(cancel)
                    .addComponent(save)
                    .addComponent(completed))
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, javax.swing.event.ChangeListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == alert) {
                TaskDetailsDialog.this.alertActionPerformed(evt);
            }
            else if (evt.getSource() == remove) {
                TaskDetailsDialog.this.removeActionPerformed(evt);
            }
            else if (evt.getSource() == cancel) {
                TaskDetailsDialog.this.cancelActionPerformed(evt);
            }
            else if (evt.getSource() == save) {
                TaskDetailsDialog.this.saveActionPerformed(evt);
            }
        }

        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            if (evt.getSource() == priority) {
                TaskDetailsDialog.this.priorityStateChanged(evt);
            }
            else if (evt.getSource() == daysBefore) {
                TaskDetailsDialog.this.daysBeforeStateChanged(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void alertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertActionPerformed
        daysBefore.setEnabled(alert.isSelected());
        alertLabel.setEnabled(alert.isSelected());
    }//GEN-LAST:event_alertActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        taskManager.removeTask(getTask().getId());
    }//GEN-LAST:event_removeActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
            if (isNewTask()) {
                taskManager.addTask(getTask());
            } else {
                taskManager.updateTask(getTask());
            }
        } catch (ValidationException ex) {
            Exceptions.printStackTrace(ex);
        }
        cancel.doClick();
    }//GEN-LAST:event_saveActionPerformed

    private void priorityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_priorityStateChanged
        priority.removeChangeListener(formListener);
        int value = (int) priority.getValue();
        if (value < 0) {
            priority.setValue(0);
        }
        if (value > 100) {
            priority.setValue(100);
        }
        priority.addChangeListener(formListener);
    }//GEN-LAST:event_priorityStateChanged

    private void daysBeforeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_daysBeforeStateChanged
        daysBefore.removeChangeListener(formListener);
        int value = (int) daysBefore.getValue();
        if (value < 0) {
            daysBefore.setValue(0);
        }
        if (value > 100) {
            daysBefore.setValue(100);   // arbitrary upper bound
        }
        daysBefore.addChangeListener(formListener);
    }//GEN-LAST:event_daysBeforeStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TaskDetailsDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    private FormListener formListener;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alert;
    private javax.swing.JLabel alertLabel;
    private javax.swing.JButton cancel;
    private javax.swing.JCheckBox completed;
    private javax.swing.JSpinner daysBefore;
    private javax.swing.JTextField description;
    private org.jdesktop.swingx.JXDatePicker dueDate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel message;
    private javax.swing.JTextArea obs;
    private javax.swing.JSpinner priority;
    private javax.swing.JButton remove;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables

}
